# Generated by Django 3.1.7 on 2021-04-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('dni', models.CharField(max_length=32)),
                ('birth_at', models.DateField()),
                ('started_at', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=128, null=True)),
                ('phone_number', models.CharField(max_length=16)),
                ('role', models.ManyToManyField(blank=True, null=True, to='shop.Role')),
            ],
        ),
    ]
